// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'titleB': string;
  'titleC': string;
}
declare const cssExports: CssExports;
export = cssExports;
